### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.date'

### ISSUE THREAD

**Issue by yiyualt** [smartschat/tilse#3]
Hello, Smartschat,  when I run **predict-timelines** I met with the error described as the title **"TypeError: '<' not supported between instances of 'NoneType' and 'datetime.date'"**.  Could you give me some hint about the error? Thank you in advance. 

My machine is mac os, **Python version is "3.7.3"** and the needed python library is indeed the version you give in other issues.  I tried different machines and different versions of python, but it gives my the same error. It is as follows: 

`Traceback (most recent call last):
  File "/Users/yoki/ubuntu1/tilse-master/venv/bin/predict-timelines", line 86, in <module>
    returned_timelines, scores = algorithm.run(news_corpora, reference_timelines)
  File "/Users/yoki/ubuntu1/tilse-master/venv/lib/python3.7/site-packages/tilse/models/models.py", line 76, in run
    reference_timelines)
  File "/Users/yoki/ubuntu1/tilse-master/venv/lib/python3.7/site-packages/tilse/models/models.py", line 96, in _run_for_one
    timeline_properties = self.get_timeline_properties(timeline)
  File "/Users/yoki/ubuntu1/tilse-master/venv/lib/python3.7/site-packages/tilse/models/models.py", line 125, in get_timeline_properties
    groundtruth_dates = sorted(list(timeline.get_dates()))
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.date'
`

followed by the **predict-timelines** command.

**Comment by yiyualt** [comment]
Sorry for this issue, it runs successfully now.

**Comment by Uzw103** [comment]
> Sorry for this issue, it runs successfully now.



> Hello, Smartschat, when I run **predict-timelines** I met with the error described as the title **"TypeError: '<' not supported between instances of 'NoneType' and 'datetime.date'"**. Could you give me some hint about the error? Thank you in advance.
> 
> My machine is mac os, **Python version is "3.7.3"** and the needed python library is indeed the version you give in other issues. I tried different machines and different versions of python, but it gives my the same error. It is as follows:
> 
> `Traceback (most recent call last): File "/Users/yoki/ubuntu1/tilse-master/venv/bin/predict-timelines", line 86, in <module> returned_timelines, scores = algorithm.run(news_corpora, reference_timelines) File "/Users/yoki/ubuntu1/tilse-master/venv/lib/python3.7/site-packages/tilse/models/models.py", line 76, in run reference_timelines) File "/Users/yoki/ubuntu1/tilse-master/venv/lib/python3.7/site-packages/tilse/models/models.py", line 96, in _run_for_one timeline_properties = self.get_timeline_properties(timeline) File "/Users/yoki/ubuntu1/tilse-master/venv/lib/python3.7/site-packages/tilse/models/models.py", line 125, in get_timeline_properties groundtruth_dates = sorted(list(timeline.get_dates())) TypeError: '<' not supported between instances of 'NoneType' and 'datetime.date' `
> 
> followed by the **predict-timelines** command.

Hello yiyualt! I encountered the same issue as you depicted above. May I ask how you fixed this issue? This pazzled me a lot :( Thank you!
