### ISSUE TITLE
Typo in Evaluation.md

### ISSUE THREAD

**Issue by ivo-1** [smartschat/tilse#4]
There is a typo in the Evaluation.md regarding how the metric tests can be invoked:
`run-timeline-metric-tests -t /path/to/timelines`

whereas it should be:
`run-timeline-metrics-tests -t /path/to/timelines`

Hope this will save anyone at least a little bit of time.

**Comment by smartschat** [comment]
Thank you for spotting the error! Fixed in 7cd812f.
